### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Tantrum90** [MrQuackDuck/TicTacToe#2]
24.06 22:32:00 [Server] WARN Nag author(s): '[]' of 'TicTacToe v1.2' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

version
24.06 22:03:17 [Server] INFO This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

version of plugin
24.06 22:34:47 [Server] INFO TicTacToe version 1.2

**Comment by MrQuackDuck** [comment]
Fixed in new release! ♥
